chain = "/root/.playground/devnet/genesis.json"
reth_datadir = "/root/.playground/devnet/data_reth"
relay_secret_key = "5eae315483f028b5cdd5d1090ff0c7618b18737ea9bf3c35047189db22835c48"
el_node_ipc_path = "/root/.playground/devnet/reth.ipc"
live_builders = ["mgp-ordering"]
enabled_relays = ["playground"]
log_level = "info,rbuilder=debug"
coinbase_secret_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
jsonrpc_server_ip = "0.0.0.0"
jsonrpc_server_port = 8645
